# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If nvim exist, use it as prefered editor, if not just use nano
if command -v nvim &>/dev/null; then
	export EDITOR=nvim
else
	export EDITOR=nano
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Sourcing aliases
if [ -d ~/.aliases/ ]; then
	# Loop through all .sh files in the aliases directory and source them
	for file in ~/.aliases/*.sh; do
		if [ -f "$file" ]; then
			source "$file"
		fi
	done
else
	echo "Aliases directory not found"
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc
