# Set terminal to true colors
set -g default-terminal 'screen-256color'
set -ag terminal-overrides ",alacritty:RGB"

# Rebind prefix key to Ctrl+Space
unbind C-b
set-option -g prefix C-s

# Rebind the splits
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Add mouse support
set -g mouse on

# vi keymode
setw -g mode-keys vi

# start windows and panes from 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# enable yazi to passtrough preview
set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
